#!/usr/bin/env python3
"""Generate `wcpred/thirds_table.py` from the official FIFA allocation grid.

The 2026 World Cup advances the 8 best third-placed teams (of 12 groups). Which
third-placed team plays which group winner in the Round of 32 is *not* a simple
rule — FIFA publishes a fixed 495-row table (one row per C(12,8) combination of
which groups supplied a third), Annex C of the tournament regulations, mirrored
on Wikipedia's "2026 FIFA World Cup knockout stage" page.

This one-off script parses that table with `pandas.read_html` and emits the
`THIRD_PLACE_ALLOCATION` literal the simulator imports. Run it by hand when the
table changes; it is never imported at runtime.

The Wikipedia table's third-place slot columns are headed by the *group winner*
(`1A vs`, `1E vs`, ...), so we map each winner to its Round-of-32 match number:

    A->79  B->85  D->81  E->74  G->82  I->77  K->87  L->80

Usage:
    # SSL in this sandbox can't verify Wikipedia's cert from Python directly,
    # so download once with curl, then point the script at the local file:
    curl -sL https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage \
        -o /tmp/wc_ko.html
    python3 scripts/build_thirds_table.py /tmp/wc_ko.html

    # ...or pass nothing to fetch the live URL (needs working SSL):
    python3 scripts/build_thirds_table.py
"""
import sys
from pathlib import Path

import pandas as pd

URL = "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_knockout_stage"
OUT = Path(__file__).resolve().parent.parent / "wcpred" / "thirds_table.py"

# Round-of-32 match number for each group winner that hosts a third-placed team.
WINNER_TO_MATCH = {"A": "M79", "B": "M85", "D": "M81", "E": "M74",
                   "G": "M82", "I": "M77", "K": "M87", "L": "M80"}
GROUPS = list("ABCDEFGHIJKL")
THIRD_SLOTS = sorted(WINNER_TO_MATCH.values(), key=lambda m: int(m[1:]))


def parse(source):
    """Parse the 495-row allocation table from a URL or local HTML file."""
    tables = pd.read_html(source)
    grid = next(t for t in tables if t.shape == (495, 22))

    # Columns: [No.] + 12 "advances from group" cols (A..L, letter or NaN) +
    # a spacer + 8 "1X vs" matchup cols whose cells are the assigned third "3Y".
    group_cols = list(grid.columns[1:13])
    vs_cols = [c for c in grid.columns if isinstance(c, str) and c.endswith(" vs")]
    assert len(vs_cols) == 8, f"expected 8 matchup columns, got {vs_cols}"

    allocation = {}
    for _, row in grid.iterrows():
        qualified = tuple(sorted(
            str(row[c]).strip() for c in group_cols if pd.notna(row[c])))
        assert len(qualified) == 8 and set(qualified) <= set(GROUPS), qualified
        slots = {}
        for c in vs_cols:
            winner = c[1]                       # "1E vs" -> "E"
            third = str(row[c]).strip()[-1]     # "3F" -> "F"
            slots[WINNER_TO_MATCH[winner]] = third
        allocation[qualified] = slots
    return allocation


def validate(allocation):
    """Structural invariants that catch transcription/parsing errors."""
    assert len(allocation) == 495, f"expected 495 rows, got {len(allocation)}"
    seen = set()
    for combo, slots in allocation.items():
        assert combo not in seen, f"duplicate combo {combo}"
        seen.add(combo)
        assert len(combo) == 8 and sorted(combo) == list(combo)
        assert set(slots) == set(THIRD_SLOTS), f"bad slots for {combo}: {slots}"
        # The assigned thirds must be exactly the 8 qualified groups (bijection).
        assert sorted(slots.values()) == sorted(combo), \
            f"not a bijection for {combo}: {slots}"
    # Spot-check row 1 (groups E..L) against the published grid.
    row1 = allocation[("E", "F", "G", "H", "I", "J", "K", "L")]
    assert row1 == {"M79": "E", "M85": "J", "M81": "I", "M74": "F",
                    "M82": "H", "M77": "G", "M87": "L", "M80": "K"}, row1
    print(f"OK: {len(allocation)} combinations, bijection + spot-check pass")


def emit(allocation):
    lines = [
        '"""Official FIFA 2026 third-place allocation table (Annex C).',
        "",
        "AUTO-GENERATED by scripts/build_thirds_table.py — do not edit by hand.",
        "",
        "Maps the set of 8 groups whose third-placed team qualifies (sorted",
        "tuple of group letters) to {Round-of-32 match id: group letter of the",
        "third-placed team assigned to that match}.",
        '"""',
        "THIRD_PLACE_ALLOCATION = {",
    ]
    for combo in sorted(allocation):
        slots = allocation[combo]
        slot_str = ", ".join(f'"{m}": "{slots[m]}"' for m in THIRD_SLOTS)
        lines.append(f"    {combo!r}: {{{slot_str}}},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else URL
    alloc = parse(src)
    validate(alloc)
    emit(alloc)
